## EDA

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.preprocessing import StandardScaler
import io
from sklearn.impute import KNNImputer
from IPython.display import display
import sys
import missingno as msno
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
from sklearn.inspection import permutation_importance
from sklearn.feature_selection import RFE, RFECV
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
from sklearn.pipeline import Pipeline



pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.4f}'.format)
sns.set_theme(style='whitegrid', palette='Set2')
%matplotlib inline

In [4]:
file_path = 'term-deposit-marketing-2020.csv'
df = pd.read_csv(file_path)

In [5]:
display(df.head())
display(df.tail())

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,no

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,y
39995,53,technician,married,tertiary,no,395,no,no,cellular,3,jun,107,1,no
39996,30,management,single,tertiary,no,3340,no,no,cellular,3,jun,238,3,yes
39997,54,admin,divorced,secondary,no,200,no,no,cellular,3,jun,170,1,yes
39998,34,management,married,tertiary,no,1047,no,no,cellular,3,jun,342,1,no
39999,38,technician,married,secondary,no,1442,yes,no,cellular,3,jun,113,1,no

In [6]:
print('=== SHAPE ===')
print(df.shape,'\n')
print('=== DTYPES ===')
print(df.dtypes, '\n')
print('=== NULLS ===')
print(df.isnull().sum(), '\n')
print('=== DUPES ===')
print(df.duplicated().sum(), '\n')
print('=== DESCRIBE ===')
display(df.describe(include='all'))

=== SHAPE ===
(40000, 14)

=== DTYPES ===
age          int64
job            str
marital        str
education      str
default        str
balance      int64
housing        str
loan           str
contact        str
day          int64
month          str
duration     int64
campaign     int64
y              str
dtype: object

=== NULLS ===
age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
y            0
dtype: int64

=== DUPES ===
0

=== DESCRIBE ===

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,y
count,40000.0000,40000,40000,40000,40000,40000.0000,40000,40000,40000,40000.0000,40000,40000.0000,40000.0000,40000
unique,NaN,12,3,4,2,NaN,2,2,3,NaN,11,NaN,NaN,2
top,NaN,blue-collar,married,secondary,no,NaN,yes,no,cellular,NaN,may,NaN,NaN,no
freq,NaN,9383,24386,20993,39191,NaN,24031,33070,24914,NaN,13532,NaN,NaN,37104
mean,40.5446,NaN,NaN,NaN,NaN,1274.2776,NaN,NaN,NaN,16.0172,NaN,254.8243,2.8822,NaN
std,9.6418,NaN,NaN,NaN,NaN,2903.7697,NaN,NaN,NaN,8.2781,NaN,259.3665,3.2391,NaN
min,19.0000,NaN,NaN,NaN,NaN,-8019.0000,NaN,NaN,NaN,1.0000,NaN,0.0000,1.0000,NaN
25%,33.0000,NaN,NaN,NaN,NaN,54.0000,NaN,NaN,NaN,8.0000,NaN,100.0000,1.0000,NaN
50%,39.0000,NaN,NaN,NaN,NaN,407.0000,NaN,NaN,NaN,17.0000,NaN,175.0000,2.0000,NaN
75%,48.0000,NaN,NaN,NaN,NaN,1319.0000,NaN,NaN,NaN,21.0000,NaN,313.0000,3.0000,NaN
max,95.0000,NaN,NaN,NaN,NaN,102127.0000,NaN,NaN,NaN,31.0000,NaN,4918.0000,63.0000,NaN

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        40000 non-null  int64
 1   job        40000 non-null  str
 2   marital    40000 non-null  str
 3   education  40000 non-null  str
 4   default    40000 non-null  str
 5   balance    40000 non-null  int64
 6   housing    40000 non-null  str
 7   loan       40000 non-null  str
 8   contact    40000 non-null  str
 9   day        40000 non-null  int64
 10  month      40000 non-null  str
 11  duration   40000 non-null  int64
 12  campaign   40000 non-null  int64
 13  y          40000 non-null  str
dtypes: int64(5), str(9)
memory usage: 4.3 MB